baseURL = "https://neurofeeders.com/"
languageCode = "en-us"
title = "Neuro Feeders"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.161.1"

[params]
  google_analytics_id = ""
  twitter_handle = "@neurofeeders"

  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  showIntroContentOnHomepage = true

  addFrame = true
  addDot = false

  highlightColor = '#d82478'

[markup.goldmark.renderer]
unsafe = true
